# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12566f62acdbd416b9400e81773bb9a7b381634aa4137e13404afaed552e7b833d78044948cc57934d55c70dd54e00bc794ab2871560147fcb5a6a656e6f1d4f

test:
  secret_key_base: 4080bd8d09e7b31492fa531fdd6d52baf81d0d399cda4f15982f2cb897e5dafb3bc59baff1bb4a0265f236dc15d6f099d06beb79a1a5ad988b97508150c88701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
